// js/flags.js
// Mapa de nombre de equipo (inglés, como devuelve la API) → emoji bandera

window.getFlag = function(teamName) {
    if (!teamName) return '🏳️';

    const flagMap = {
        // Principales selecciones mundiales
        'Argentina': '🇦🇷',
        'Australia': '🇦🇺',
        'Belgium': '🇧🇪',
        'Brazil': '🇧🇷',
        'Cameroon': '🇨🇲',
        'Canada': '🇨🇦',
        'Chile': '🇨🇱',
        'Colombia': '🇨🇴',
        'Costa Rica': '🇨🇷',
        'Croatia': '🇭🇷',
        'Czech Republic': '🇨🇿',
        'Czechia': '🇨🇿',
        'Denmark': '🇩🇰',
        'Ecuador': '🇪🇨',
        'Egypt': '🇪🇬',
        'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
        'France': '🇫🇷',
        'Germany': '🇩🇪',
        'Ghana': '🇬🇭',
        'Greece': '🇬🇷',
        'Honduras': '🇭🇳',
        'Hungary': '🇭🇺',
        'Iran': '🇮🇷',
        'Islamic Republic of Iran': '🇮🇷',
        'Italy': '🇮🇹',
        'Japan': '🇯🇵',
        'Mexico': '🇲🇽',
        'Morocco': '🇲🇦',
        'Netherlands': '🇳🇱',
        'Nigeria': '🇳🇬',
        'Norway': '🇳🇴',
        'Panama': '🇵🇦',
        'Paraguay': '🇵🇾',
        'Peru': '🇵🇪',
        'Poland': '🇵🇱',
        'Portugal': '🇵🇹',
        'Qatar': '🇶🇦',
        'Romania': '🇷🇴',
        'Saudi Arabia': '🇸🇦',
        'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        'Senegal': '🇸🇳',
        'Serbia': '🇷🇸',
        'Slovakia': '🇸🇰',
        'Slovenia': '🇸🇮',
        'South Korea': '🇰🇷',
        'Korea Republic': '🇰🇷',
        'Spain': '🇪🇸',
        'Sweden': '🇸🇪',
        'Switzerland': '🇨🇭',
        'Tunisia': '🇹🇳',
        'Turkey': '🇹🇷',
        'Türkiye': '🇹🇷',
        'Ukraine': '🇺🇦',
        'United States': '🇺🇸',
        'USA': '🇺🇸',
        'US': '🇺🇸',
        'Uruguay': '🇺🇾',
        'Venezuela': '🇻🇪',
        'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
        'Albania': '🇦🇱',
        'Algeria': '🇩🇿',
        'Angola': '🇦🇴',
        'Austria': '🇦🇹',
        'Bolivia': '🇧🇴',
        'Bosnia and Herzegovina': '🇧🇦',
        "Côte d'Ivoire": '🇨🇮',
        'Ivory Coast': '🇨🇮',
        'China': '🇨🇳',
        'China PR': '🇨🇳',
        'Cuba': '🇨🇺',
        'DR Congo': '🇨🇩',
        'Finland': '🇫🇮',
        'Guatemala': '🇬🇹',
        'Guinea': '🇬🇳',
        'Haiti': '🇭🇹',
        'India': '🇮🇳',
        'Indonesia': '🇮🇩',
        'Iraq': '🇮🇶',
        'Ireland': '🇮🇪',
        'Republic of Ireland': '🇮🇪',
        'Israel': '🇮🇱',
        'Jamaica': '🇯🇲',
        'Jordan': '🇯🇴',
        'Kenya': '🇰🇪',
        'Kosovo': '🇽🇰',
        'Libya': '🇱🇾',
        'Luxembourg': '🇱🇺',
        'Mali': '🇲🇱',
        'Mauritania': '🇲🇷',
        'Mozambique': '🇲🇿',
        'New Zealand': '🇳🇿',
        'Nicaragua': '🇳🇮',
        'North Korea': '🇰🇵',
        'North Macedonia': '🇲🇰',
        'Oman': '🇴🇲',
        'Palestine': '🇵🇸',
        'Philippines': '🇵🇭',
        'South Africa': '🇿🇦',
        'El Salvador': '🇸🇻',
        'Suriname': '🇸🇷',
        'Tajikistan': '🇹🇯',
        'Thailand': '🇹🇭',
        'Trinidad and Tobago': '🇹🇹',
        'Uganda': '🇺🇬',
        'United Arab Emirates': '🇦🇪',
        'Uzbekistan': '🇺🇿',
        'Vietnam': '🇻🇳',
        'Zambia': '🇿🇲',
        'Zimbabwe': '🇿🇼',
        'Curaçao': '🇨🇼',
        // Nombres en español (por si los equipos locales los usan)
        'Alemania': '🇩🇪',
        'España': '🇪🇸',
        'Francia': '🇫🇷',
        'Italia': '🇮🇹',
        'Portugal': '🇵🇹',
        'Países Bajos': '🇳🇱',
        'Dinamarca': '🇩🇰',
        'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
        'Gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
        'Suiza': '🇨🇭',
        'Suecia': '🇸🇪',
        'Noruega': '🇳🇴',
        'Croacia': '🇭🇷',
        'Polonia': '🇵🇱',
        'Serbia': '🇷🇸',
        'Turquía': '🇹🇷',
        'Rumanía': '🇷🇴',
        'Grecia': '🇬🇷',
        'México': '🇲🇽',
        'Japón': '🇯🇵',
        'Corea del Sur': '🇰🇷',
        'Arabia Saudí': '🇸🇦',
        'Marruecos': '🇲🇦',
        'Costa de Marfil': '🇨🇮',
    };

    // Búsqueda exacta primero
    if (flagMap[teamName]) return flagMap[teamName];

    // Búsqueda parcial como fallback
    const lower = (teamName || '').toLowerCase();
    for (const [key, val] of Object.entries(flagMap)) {
        if (lower === key.toLowerCase()) return val;
    }
    for (const [key, val] of Object.entries(flagMap)) {
        if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) return val;
    }

    return '🏳️'; // Bandera genérica por defecto
};
